- walls:
    walls:
      name: walls
      pos: [0, 0, 0]
      geoms:
        - euler:
          - 0
          - 0
          - 0
          group: 2
          name: wall_0
          pos:
          - 0.34500000000000003
          - 0.05
          - 0.5
          rgba:
          - 1.0
          - 1.0
          - 1.0
          - 0.5
          size:
          - 0.245
          - 0.5
          - 0.5
          type: box
        - euler:
          - 0
          - 0
          - 0
          group: 2
          name: wall_1
          pos:
          - 0.12
          - 0.1
          - 0.5
          rgba:
          - 1.0
          - 1.0
          - 1.0
          - 0.5
          size:
          - 0.02
          - 0.5
          - 0.5
          type: box
